version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app:latest
    container_name: laravel_app
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    environment:
      APP_URL: http://nio.com
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: organization
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - "80:80"
    networks:
      - laravel_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: organization
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravel_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - laravel_network

  # vite:
  #   image: node:18-alpine
  #   container_name: laravel_vite
  #   working_dir: /var/www
  #   volumes:
  #     - .:/var/www
  #   networks:
  #     - laravel_network
  #   environment:
  #     PATH: /root/.bun/bin:$PATH
  #   depends_on:
  #     - app
  #   init: true # Ensures proper handling of initialization

volumes:
  mysql_data:

networks:
  laravel_network:
    driver: bridge
 